CREATE DATABASE '/tmp/test.db' user 'SYSDBA' password '1234';

CREATE TABLE TABLE1 (ID INT, NAME VARCHAR(256));

INSERT INTO TABLE1 (ID, NAME) VALUES (1, 'Fulano');
INSERT INTO TABLE1 (ID, NAME) VALUES (2, 'Beltrano');
INSERT INTO TABLE1 (ID, NAME) VALUES (3, 'Ciclano');
INSERT INTO TABLE1 (ID, NAME) VALUES (4, 'Zestrano');

